### ISSUE TITLE
Generalisations needed

### ISSUE THREAD

**Issue by Ridhwanluthra** [ros-planning/moveit_grasps#2]
@mlautman @v4hn @feroze
Will use this issue to keep track of wherever generalisation is needed. Will keep updating as a task list here and giving details in comments or separate issues whatever seems appropriate.

- [ ] grasp_data.cpp
  - [ ] Starting [here](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/grasp_data.cpp#L233) to end of function.
  - [ ] [this](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/grasp_data.cpp#L277)
- [ ] grasp_generator.cpp
  - [ ] [this](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/grasp_generator.cpp#L673)
- [ ] grasp_generator_test.cpp
  - [ ] [It](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/test/grasp_generator_test.cpp#L101) is used for scoring but would be different for different objects right?

**Comment by Ridhwanluthra** [comment]
@mlautman @v4hn @feroze

**Comment by davetcoleman** [comment]
I believe this repo has been greatly generalized and this issue can be closed...
