### ISSUE TITLE
Object Missing

### ISSUE THREAD

**Issue by yanwangoakland** [ros-planning/moveit_grasps#23]
Hi, I am using the latest moveit_grasps package. 

I met a problem that when I launch the first command: roslaunch moveit_grasps rviz.launch

I can see the baxter robot but I cannot found any object for baxter grasp.  Can anyone tell me how to add the object to the rviz for baxter to grasp?

When I run the second command:roslaunch moveit_grasps test_grasp_generator.launch 
The baxter no any operation in rviz. Can anyone give me some suggestion?
The result shown [here](https://github.com/yanwangoakland/yanwang/blob/master/Baxter%20Error)

Thanks!

![screenshot from 2018-09-23 22-54-44](https://user-images.githubusercontent.com/37948484/45936467-e72eea80-bf84-11e8-8bc0-0c55f1ee1cac.png)

**Comment by MohmadAyman** [comment]
I've had the same problem.
I believe the README is outdated, two of the launch files mentioned are not in the package.

**Comment by davetcoleman** [comment]
Closing this issue as @mlautman has greatly refactored this effort and its working for several of our clients now.

Please re-open if you still have an issue on this.
