### ISSUE TITLE
usage of setGraspWidth and setting of pre_grasp_posture

### ISSUE THREAD

**Issue by Ridhwanluthra** [ros-planning/moveit_grasps#7]
We take the pre_grasp_posture from the user in robot configuration files.
Then while setting we use this function [setGraspWidth](https://github.com/davetcoleman/moveit_grasps/blob/kinetic-devel/src/grasp_data.cpp#L199) which requires specific information about the robot.
Could you please comment on the need for this. Also, if we use this then why take pre_grasp_posture from the user separately.

I was thinking that maybe it made sense to get the max and min of each joint and take grasp posture from the user and take the percent in the ratio of the grasp posture given by the user. I think that would solve the purpose of needing this function and also make it generalised.

**Comment by davetcoleman** [comment]
Closing this issue as @mlautman has greatly refactored this effort and its working for several of our clients now.
