### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by mlautman** [ros-planning/moveit_grasps#85]
@henningkayser and @JafarAbdi Building the master branch I get the following error. Is that to be expected? 
```
--- stderr: moveit_ros_planning                           
CMake Error at /home/mike/ws_moveit2/install/moveit_core/share/moveit_core/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
  Package 'moveit_core' exports the library 'moveit_exceptions' which
  couldn't be found
Call Stack (most recent call first):
  /home/mike/ws_moveit2/install/moveit_core/share/moveit_core/cmake/moveit_coreConfig.cmake:38 (include)
  CMakeLists.txt:26 (find_package)
```

**Comment by JafarAbdi** [comment]
@mlautman Are you building it with `--symlink-install` flag .? if yes, there was a bug which got fixed in this [PR](https://github.com/ament/ament_cmake/pull/216) .?

**Comment by mlautman** [comment]
I used the same build command as is in moveit_ci `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O3 --catkin-cmake-args -DCMAKE_BUILD_TYPE`

**Comment by mlautman** [comment]
I removed all the build artifacts and re-built and things went well. Thanks
