### ISSUE TITLE
Runtime Error : grasp_pipeline_demo

### ISSUE THREAD

**Issue by HasanFarag** [ros-planning/moveit_grasps#94]
when running grasp_pipeline_demo, I see log message "Filtering 144 candidate grasps with 1 threads" and I have a exit code -11 (which is core dumped because of Invalid memory reference). I tried to track the commits on melodic-devel to check as i am using that branch. Noting that: other demos work fine. Can you help me in that?

**Comment by Dale-Koenig** [comment]
Can you compile in debug mode, then run with the launch argument `debug:=true` and get the backtrace with `bt` when gdb opens after the crash?

**Comment by mlautman** [comment]
closing for now assuming @HasanFarag has figured out the issue. Feel free to re-open if you are still having the issue
